# Generated by Django 3.2.9 on 2021-11-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_phase', models.IntegerField(default=0)),
                ('structure', models.CharField(max_length=200)),
                ('inchi_key', models.CharField(max_length=27)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('units', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
                ('relation', models.CharField(max_length=2)),
                ('target_id', models.IntegerField(default=0)),
                ('molecule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.molecule')),
            ],
        ),
    ]
